// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SharedModel.Model;

#nullable disable

namespace SharedModel.Migrations
{
    [DbContext(typeof(CardContext))]
    [Migration("20211127150331_AddRecord")]
    partial class AddRecord
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardRecord", b =>
                {
                    b.Property<Guid>("CardsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecordsId")
                        .HasColumnType("uuid");

                    b.HasKey("CardsId", "RecordsId");

                    b.HasIndex("RecordsId");

                    b.ToTable("CardRecord");
                });

            modelBuilder.Entity("SharedModel.Model.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Layout")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("SharedModel.Model.Face", b =>
                {
                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Loyalty")
                        .HasColumnType("text");

                    b.Property<string>("ManaCost")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OracleText")
                        .HasColumnType("text");

                    b.Property<string>("Power")
                        .HasColumnType("text");

                    b.Property<string>("Toughness")
                        .HasColumnType("text");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CardId", "Sequence");

                    b.ToTable("Face");
                });

            modelBuilder.Entity("SharedModel.Model.NameIndex", b =>
                {
                    b.Property<string>("SanitizedName")
                        .HasColumnType("text");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.HasKey("SanitizedName");

                    b.HasIndex("CardId");

                    b.ToTable("Index");
                });

            modelBuilder.Entity("SharedModel.Model.Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<string>>("UnrecognizedCards")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("When")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("SharedModel.Model.Update", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("When")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Updates");
                });

            modelBuilder.Entity("CardRecord", b =>
                {
                    b.HasOne("SharedModel.Model.Card", null)
                        .WithMany()
                        .HasForeignKey("CardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedModel.Model.Record", null)
                        .WithMany()
                        .HasForeignKey("RecordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharedModel.Model.Face", b =>
                {
                    b.HasOne("SharedModel.Model.Card", null)
                        .WithMany("Faces")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharedModel.Model.NameIndex", b =>
                {
                    b.HasOne("SharedModel.Model.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("SharedModel.Model.Card", b =>
                {
                    b.Navigation("Faces");
                });
#pragma warning restore 612, 618
        }
    }
}
